//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EShop.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Goods
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Goods()
        {
            this.OrdersGoods = new HashSet<OrdersGoods>();
        }
    
        public int GoodsID { get; set; }
        public string GName { get; set; }
        public string Firm { get; set; }
        public string Model { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string Specifications { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> WarrantyPerMonth { get; set; }
        public string GImage { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdersGoods> OrdersGoods { get; set; }
    }
}
