//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EShop.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orders()
        {
            this.OrdersGoods = new HashSet<OrdersGoods>();
        }
    
        public int OrdersID { get; set; }
        public Nullable<int> StoreID { get; set; }
        public Nullable<int> WayToGetID { get; set; }
        public Nullable<int> DeliveryID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Delivery Delivery { get; set; }
        public virtual Status Status { get; set; }
        public virtual Store Store { get; set; }
        public virtual WayToGet WayToGet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdersGoods> OrdersGoods { get; set; }
    }
}
